"""Add level field in user

Revision ID: 10c6065e6f1
Revises: 41732f6271a
Create Date: 2015-10-21 20:10:55.616353

"""

# revision identifiers, used by Alembic.
revision = '10c6065e6f1'
down_revision = '41732f6271a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    pass


def downgrade_():
    pass


def upgrade_auth():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('level', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_auth():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'level')
    ### end Alembic commands ###

