"""add last update flag in posts

Revision ID: 3957db5c0ca
Revises: ee05faad51
Create Date: 2015-10-27 10:18:42.925759

"""

# revision identifiers, used by Alembic.
revision = '3957db5c0ca'
down_revision = 'ee05faad51'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    pass


def downgrade_():
    pass


def upgrade_amblog():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('last_updated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade_amblog():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'last_updated')
    ### end Alembic commands ###


def upgrade_auth():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_auth():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

