"""update posts

Revision ID: 4263ac698e3
Revises: 49936137581
Create Date: 2015-10-26 15:27:30.522091

"""

# revision identifiers, used by Alembic.
revision = '4263ac698e3'
down_revision = '49936137581'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    pass


def downgrade_():
    pass


def upgrade_auth():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_auth():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_amblog():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('publish', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('publish_time', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    ### end Alembic commands ###


def downgrade_amblog():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_ibfk_1', 'posts', 'category', ['category_id'], ['id'])
    op.drop_column('posts', 'update_time')
    op.drop_column('posts', 'publish_time')
    op.drop_column('posts', 'publish')
    op.drop_column('posts', 'create_time')
    ### end Alembic commands ###

