"""init

Revision ID: 49936137581
Revises: 2545ec72ec7
Create Date: 2015-10-23 12:25:24.854730

"""

# revision identifiers, used by Alembic.
revision = '49936137581'
down_revision = '2545ec72ec7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    pass


def downgrade_():
    pass


def upgrade_amblog():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'category', ['category_id'], ['id'])
    op.drop_column('posts', 'category')
    ### end Alembic commands ###


def downgrade_amblog():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_ibfk_1', 'posts', 'category', ['category'], ['id'])
    op.drop_column('posts', 'category_id')
    ### end Alembic commands ###


def upgrade_auth():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_auth():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

