"""allow post title same

Revision ID: e84d31944b
Revises: 3957db5c0ca
Create Date: 2015-10-27 16:58:32.548170

"""

# revision identifiers, used by Alembic.
revision = 'e84d31944b'
down_revision = '3957db5c0ca'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    pass


def downgrade_():
    pass


def upgrade_amblog():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='posts')
    op.drop_index('title_2', table_name='posts')
    ### end Alembic commands ###


def downgrade_amblog():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title_2', 'posts', ['title'], unique=True)
    op.create_index('title', 'posts', ['title'], unique=True)
    ### end Alembic commands ###


def upgrade_auth():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_auth():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

